// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_events_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_events_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "events/connector.pb.h"
#include "events/strategy.pb.h"
#include "trading.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_events_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_events_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_events_2eproto;
namespace markethub {
namespace messaging {
namespace events {
class EventWrapper;
struct EventWrapperDefaultTypeInternal;
extern EventWrapperDefaultTypeInternal _EventWrapper_default_instance_;
}  // namespace events
}  // namespace messaging
}  // namespace markethub
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace markethub {
namespace messaging {
namespace events {

// ===================================================================


// -------------------------------------------------------------------

class EventWrapper final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:markethub.messaging.events.EventWrapper) */ {
 public:
  inline EventWrapper() : EventWrapper(nullptr) {}
  ~EventWrapper() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EventWrapper(
      ::google::protobuf::internal::ConstantInitialized);

  inline EventWrapper(const EventWrapper& from) : EventWrapper(nullptr, from) {}
  inline EventWrapper(EventWrapper&& from) noexcept
      : EventWrapper(nullptr, std::move(from)) {}
  inline EventWrapper& operator=(const EventWrapper& from) {
    CopyFrom(from);
    return *this;
  }
  inline EventWrapper& operator=(EventWrapper&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EventWrapper& default_instance() {
    return *internal_default_instance();
  }
  enum EventCase {
    kOnBookGenerated = 4,
    kExecutionReport = 5,
    kStrategyExecutionStarted = 6,
    kOnData = 7,
    kEndOnData = 8,
    kOnExecutionReport = 9,
    kStatistics = 10,
    kOnParamsChanged = 11,
    EVENT_NOT_SET = 0,
  };
  static inline const EventWrapper* internal_default_instance() {
    return reinterpret_cast<const EventWrapper*>(
        &_EventWrapper_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EventWrapper& a, EventWrapper& b) { a.Swap(&b); }
  inline void Swap(EventWrapper* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EventWrapper* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EventWrapper* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<EventWrapper>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EventWrapper& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EventWrapper& from) { EventWrapper::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(EventWrapper* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "markethub.messaging.events.EventWrapper"; }

 protected:
  explicit EventWrapper(::google::protobuf::Arena* arena);
  EventWrapper(::google::protobuf::Arena* arena, const EventWrapper& from);
  EventWrapper(::google::protobuf::Arena* arena, EventWrapper&& from) noexcept
      : EventWrapper(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEventTypeFieldNumber = 1,
    kEventIdFieldNumber = 2,
    kClientIdFieldNumber = 3,
    kOnBookGeneratedFieldNumber = 4,
    kExecutionReportFieldNumber = 5,
    kStrategyExecutionStartedFieldNumber = 6,
    kOnDataFieldNumber = 7,
    kEndOnDataFieldNumber = 8,
    kOnExecutionReportFieldNumber = 9,
    kStatisticsFieldNumber = 10,
    kOnParamsChangedFieldNumber = 11,
  };
  // string event_type = 1;
  void clear_event_type() ;
  const std::string& event_type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_event_type(Arg_&& arg, Args_... args);
  std::string* mutable_event_type();
  PROTOBUF_NODISCARD std::string* release_event_type();
  void set_allocated_event_type(std::string* value);

  private:
  const std::string& _internal_event_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_event_type(
      const std::string& value);
  std::string* _internal_mutable_event_type();

  public:
  // string event_id = 2;
  void clear_event_id() ;
  const std::string& event_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_event_id(Arg_&& arg, Args_... args);
  std::string* mutable_event_id();
  PROTOBUF_NODISCARD std::string* release_event_id();
  void set_allocated_event_id(std::string* value);

  private:
  const std::string& _internal_event_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_event_id(
      const std::string& value);
  std::string* _internal_mutable_event_id();

  public:
  // string client_id = 3;
  void clear_client_id() ;
  const std::string& client_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_client_id(Arg_&& arg, Args_... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* value);

  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(
      const std::string& value);
  std::string* _internal_mutable_client_id();

  public:
  // .markethub.messaging.trading.Book on_book_generated = 4;
  bool has_on_book_generated() const;
  private:
  bool _internal_has_on_book_generated() const;

  public:
  void clear_on_book_generated() ;
  const ::markethub::messaging::trading::Book& on_book_generated() const;
  PROTOBUF_NODISCARD ::markethub::messaging::trading::Book* release_on_book_generated();
  ::markethub::messaging::trading::Book* mutable_on_book_generated();
  void set_allocated_on_book_generated(::markethub::messaging::trading::Book* value);
  void unsafe_arena_set_allocated_on_book_generated(::markethub::messaging::trading::Book* value);
  ::markethub::messaging::trading::Book* unsafe_arena_release_on_book_generated();

  private:
  const ::markethub::messaging::trading::Book& _internal_on_book_generated() const;
  ::markethub::messaging::trading::Book* _internal_mutable_on_book_generated();

  public:
  // .markethub.messaging.trading.ExecutionReport execution_report = 5;
  bool has_execution_report() const;
  private:
  bool _internal_has_execution_report() const;

  public:
  void clear_execution_report() ;
  const ::markethub::messaging::trading::ExecutionReport& execution_report() const;
  PROTOBUF_NODISCARD ::markethub::messaging::trading::ExecutionReport* release_execution_report();
  ::markethub::messaging::trading::ExecutionReport* mutable_execution_report();
  void set_allocated_execution_report(::markethub::messaging::trading::ExecutionReport* value);
  void unsafe_arena_set_allocated_execution_report(::markethub::messaging::trading::ExecutionReport* value);
  ::markethub::messaging::trading::ExecutionReport* unsafe_arena_release_execution_report();

  private:
  const ::markethub::messaging::trading::ExecutionReport& _internal_execution_report() const;
  ::markethub::messaging::trading::ExecutionReport* _internal_mutable_execution_report();

  public:
  // .markethub.messaging.events.strategy.StrategyExecutionStarted strategy_execution_started = 6;
  bool has_strategy_execution_started() const;
  private:
  bool _internal_has_strategy_execution_started() const;

  public:
  void clear_strategy_execution_started() ;
  const ::markethub::messaging::events::strategy::StrategyExecutionStarted& strategy_execution_started() const;
  PROTOBUF_NODISCARD ::markethub::messaging::events::strategy::StrategyExecutionStarted* release_strategy_execution_started();
  ::markethub::messaging::events::strategy::StrategyExecutionStarted* mutable_strategy_execution_started();
  void set_allocated_strategy_execution_started(::markethub::messaging::events::strategy::StrategyExecutionStarted* value);
  void unsafe_arena_set_allocated_strategy_execution_started(::markethub::messaging::events::strategy::StrategyExecutionStarted* value);
  ::markethub::messaging::events::strategy::StrategyExecutionStarted* unsafe_arena_release_strategy_execution_started();

  private:
  const ::markethub::messaging::events::strategy::StrategyExecutionStarted& _internal_strategy_execution_started() const;
  ::markethub::messaging::events::strategy::StrategyExecutionStarted* _internal_mutable_strategy_execution_started();

  public:
  // .markethub.messaging.events.strategy.OnData on_data = 7;
  bool has_on_data() const;
  private:
  bool _internal_has_on_data() const;

  public:
  void clear_on_data() ;
  const ::markethub::messaging::events::strategy::OnData& on_data() const;
  PROTOBUF_NODISCARD ::markethub::messaging::events::strategy::OnData* release_on_data();
  ::markethub::messaging::events::strategy::OnData* mutable_on_data();
  void set_allocated_on_data(::markethub::messaging::events::strategy::OnData* value);
  void unsafe_arena_set_allocated_on_data(::markethub::messaging::events::strategy::OnData* value);
  ::markethub::messaging::events::strategy::OnData* unsafe_arena_release_on_data();

  private:
  const ::markethub::messaging::events::strategy::OnData& _internal_on_data() const;
  ::markethub::messaging::events::strategy::OnData* _internal_mutable_on_data();

  public:
  // .markethub.messaging.events.strategy.EndOnData end_on_data = 8;
  bool has_end_on_data() const;
  private:
  bool _internal_has_end_on_data() const;

  public:
  void clear_end_on_data() ;
  const ::markethub::messaging::events::strategy::EndOnData& end_on_data() const;
  PROTOBUF_NODISCARD ::markethub::messaging::events::strategy::EndOnData* release_end_on_data();
  ::markethub::messaging::events::strategy::EndOnData* mutable_end_on_data();
  void set_allocated_end_on_data(::markethub::messaging::events::strategy::EndOnData* value);
  void unsafe_arena_set_allocated_end_on_data(::markethub::messaging::events::strategy::EndOnData* value);
  ::markethub::messaging::events::strategy::EndOnData* unsafe_arena_release_end_on_data();

  private:
  const ::markethub::messaging::events::strategy::EndOnData& _internal_end_on_data() const;
  ::markethub::messaging::events::strategy::EndOnData* _internal_mutable_end_on_data();

  public:
  // .markethub.messaging.events.strategy.OnExecutionReport on_execution_report = 9;
  bool has_on_execution_report() const;
  private:
  bool _internal_has_on_execution_report() const;

  public:
  void clear_on_execution_report() ;
  const ::markethub::messaging::events::strategy::OnExecutionReport& on_execution_report() const;
  PROTOBUF_NODISCARD ::markethub::messaging::events::strategy::OnExecutionReport* release_on_execution_report();
  ::markethub::messaging::events::strategy::OnExecutionReport* mutable_on_execution_report();
  void set_allocated_on_execution_report(::markethub::messaging::events::strategy::OnExecutionReport* value);
  void unsafe_arena_set_allocated_on_execution_report(::markethub::messaging::events::strategy::OnExecutionReport* value);
  ::markethub::messaging::events::strategy::OnExecutionReport* unsafe_arena_release_on_execution_report();

  private:
  const ::markethub::messaging::events::strategy::OnExecutionReport& _internal_on_execution_report() const;
  ::markethub::messaging::events::strategy::OnExecutionReport* _internal_mutable_on_execution_report();

  public:
  // .markethub.messaging.events.strategy.Statistics statistics = 10;
  bool has_statistics() const;
  private:
  bool _internal_has_statistics() const;

  public:
  void clear_statistics() ;
  const ::markethub::messaging::events::strategy::Statistics& statistics() const;
  PROTOBUF_NODISCARD ::markethub::messaging::events::strategy::Statistics* release_statistics();
  ::markethub::messaging::events::strategy::Statistics* mutable_statistics();
  void set_allocated_statistics(::markethub::messaging::events::strategy::Statistics* value);
  void unsafe_arena_set_allocated_statistics(::markethub::messaging::events::strategy::Statistics* value);
  ::markethub::messaging::events::strategy::Statistics* unsafe_arena_release_statistics();

  private:
  const ::markethub::messaging::events::strategy::Statistics& _internal_statistics() const;
  ::markethub::messaging::events::strategy::Statistics* _internal_mutable_statistics();

  public:
  // .markethub.messaging.events.strategy.OnParamsChanged on_params_changed = 11;
  bool has_on_params_changed() const;
  private:
  bool _internal_has_on_params_changed() const;

  public:
  void clear_on_params_changed() ;
  const ::markethub::messaging::events::strategy::OnParamsChanged& on_params_changed() const;
  PROTOBUF_NODISCARD ::markethub::messaging::events::strategy::OnParamsChanged* release_on_params_changed();
  ::markethub::messaging::events::strategy::OnParamsChanged* mutable_on_params_changed();
  void set_allocated_on_params_changed(::markethub::messaging::events::strategy::OnParamsChanged* value);
  void unsafe_arena_set_allocated_on_params_changed(::markethub::messaging::events::strategy::OnParamsChanged* value);
  ::markethub::messaging::events::strategy::OnParamsChanged* unsafe_arena_release_on_params_changed();

  private:
  const ::markethub::messaging::events::strategy::OnParamsChanged& _internal_on_params_changed() const;
  ::markethub::messaging::events::strategy::OnParamsChanged* _internal_mutable_on_params_changed();

  public:
  void clear_event();
  EventCase event_case() const;
  // @@protoc_insertion_point(class_scope:markethub.messaging.events.EventWrapper)
 private:
  class _Internal;
  void set_has_on_book_generated();
  void set_has_execution_report();
  void set_has_strategy_execution_started();
  void set_has_on_data();
  void set_has_end_on_data();
  void set_has_on_execution_report();
  void set_has_statistics();
  void set_has_on_params_changed();
  inline bool has_event() const;
  inline void clear_has_event();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 11, 8,
      83, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_EventWrapper_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EventWrapper& from_msg);
    ::google::protobuf::internal::ArenaStringPtr event_type_;
    ::google::protobuf::internal::ArenaStringPtr event_id_;
    ::google::protobuf::internal::ArenaStringPtr client_id_;
    union EventUnion {
      constexpr EventUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::markethub::messaging::trading::Book* on_book_generated_;
      ::markethub::messaging::trading::ExecutionReport* execution_report_;
      ::markethub::messaging::events::strategy::StrategyExecutionStarted* strategy_execution_started_;
      ::markethub::messaging::events::strategy::OnData* on_data_;
      ::markethub::messaging::events::strategy::EndOnData* end_on_data_;
      ::markethub::messaging::events::strategy::OnExecutionReport* on_execution_report_;
      ::markethub::messaging::events::strategy::Statistics* statistics_;
      ::markethub::messaging::events::strategy::OnParamsChanged* on_params_changed_;
    } event_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_events_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EventWrapper

// string event_type = 1;
inline void EventWrapper::clear_event_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_type_.ClearToEmpty();
}
inline const std::string& EventWrapper::event_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.event_type)
  return _internal_event_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EventWrapper::set_event_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:markethub.messaging.events.EventWrapper.event_type)
}
inline std::string* EventWrapper::mutable_event_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_event_type();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.event_type)
  return _s;
}
inline const std::string& EventWrapper::_internal_event_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.event_type_.Get();
}
inline void EventWrapper::_internal_set_event_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_type_.Set(value, GetArena());
}
inline std::string* EventWrapper::_internal_mutable_event_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.event_type_.Mutable( GetArena());
}
inline std::string* EventWrapper::release_event_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.event_type)
  return _impl_.event_type_.Release();
}
inline void EventWrapper::set_allocated_event_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_type_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.event_type_.IsDefault()) {
          _impl_.event_type_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:markethub.messaging.events.EventWrapper.event_type)
}

// string event_id = 2;
inline void EventWrapper::clear_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_id_.ClearToEmpty();
}
inline const std::string& EventWrapper::event_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.event_id)
  return _internal_event_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EventWrapper::set_event_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:markethub.messaging.events.EventWrapper.event_id)
}
inline std::string* EventWrapper::mutable_event_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_event_id();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.event_id)
  return _s;
}
inline const std::string& EventWrapper::_internal_event_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.event_id_.Get();
}
inline void EventWrapper::_internal_set_event_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_id_.Set(value, GetArena());
}
inline std::string* EventWrapper::_internal_mutable_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.event_id_.Mutable( GetArena());
}
inline std::string* EventWrapper::release_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.event_id)
  return _impl_.event_id_.Release();
}
inline void EventWrapper::set_allocated_event_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.event_id_.IsDefault()) {
          _impl_.event_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:markethub.messaging.events.EventWrapper.event_id)
}

// string client_id = 3;
inline void EventWrapper::clear_client_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& EventWrapper::client_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.client_id)
  return _internal_client_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EventWrapper::set_client_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:markethub.messaging.events.EventWrapper.client_id)
}
inline std::string* EventWrapper::mutable_client_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.client_id)
  return _s;
}
inline const std::string& EventWrapper::_internal_client_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_id_.Get();
}
inline void EventWrapper::_internal_set_client_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_.Set(value, GetArena());
}
inline std::string* EventWrapper::_internal_mutable_client_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.client_id_.Mutable( GetArena());
}
inline std::string* EventWrapper::release_client_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.client_id)
  return _impl_.client_id_.Release();
}
inline void EventWrapper::set_allocated_client_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.client_id_.IsDefault()) {
          _impl_.client_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:markethub.messaging.events.EventWrapper.client_id)
}

// .markethub.messaging.trading.Book on_book_generated = 4;
inline bool EventWrapper::has_on_book_generated() const {
  return event_case() == kOnBookGenerated;
}
inline bool EventWrapper::_internal_has_on_book_generated() const {
  return event_case() == kOnBookGenerated;
}
inline void EventWrapper::set_has_on_book_generated() {
  _impl_._oneof_case_[0] = kOnBookGenerated;
}
inline ::markethub::messaging::trading::Book* EventWrapper::release_on_book_generated() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.on_book_generated)
  if (event_case() == kOnBookGenerated) {
    clear_has_event();
    auto* temp = _impl_.event_.on_book_generated_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.on_book_generated_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::trading::Book& EventWrapper::_internal_on_book_generated() const {
  return event_case() == kOnBookGenerated ? *_impl_.event_.on_book_generated_ : reinterpret_cast<::markethub::messaging::trading::Book&>(::markethub::messaging::trading::_Book_default_instance_);
}
inline const ::markethub::messaging::trading::Book& EventWrapper::on_book_generated() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.on_book_generated)
  return _internal_on_book_generated();
}
inline ::markethub::messaging::trading::Book* EventWrapper::unsafe_arena_release_on_book_generated() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.on_book_generated)
  if (event_case() == kOnBookGenerated) {
    clear_has_event();
    auto* temp = _impl_.event_.on_book_generated_;
    _impl_.event_.on_book_generated_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_on_book_generated(::markethub::messaging::trading::Book* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_on_book_generated();
    _impl_.event_.on_book_generated_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.on_book_generated)
}
inline ::markethub::messaging::trading::Book* EventWrapper::_internal_mutable_on_book_generated() {
  if (event_case() != kOnBookGenerated) {
    clear_event();
    set_has_on_book_generated();
    _impl_.event_.on_book_generated_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::trading::Book>(GetArena());
  }
  return _impl_.event_.on_book_generated_;
}
inline ::markethub::messaging::trading::Book* EventWrapper::mutable_on_book_generated() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::trading::Book* _msg = _internal_mutable_on_book_generated();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.on_book_generated)
  return _msg;
}

// .markethub.messaging.trading.ExecutionReport execution_report = 5;
inline bool EventWrapper::has_execution_report() const {
  return event_case() == kExecutionReport;
}
inline bool EventWrapper::_internal_has_execution_report() const {
  return event_case() == kExecutionReport;
}
inline void EventWrapper::set_has_execution_report() {
  _impl_._oneof_case_[0] = kExecutionReport;
}
inline ::markethub::messaging::trading::ExecutionReport* EventWrapper::release_execution_report() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.execution_report)
  if (event_case() == kExecutionReport) {
    clear_has_event();
    auto* temp = _impl_.event_.execution_report_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.execution_report_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::trading::ExecutionReport& EventWrapper::_internal_execution_report() const {
  return event_case() == kExecutionReport ? *_impl_.event_.execution_report_ : reinterpret_cast<::markethub::messaging::trading::ExecutionReport&>(::markethub::messaging::trading::_ExecutionReport_default_instance_);
}
inline const ::markethub::messaging::trading::ExecutionReport& EventWrapper::execution_report() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.execution_report)
  return _internal_execution_report();
}
inline ::markethub::messaging::trading::ExecutionReport* EventWrapper::unsafe_arena_release_execution_report() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.execution_report)
  if (event_case() == kExecutionReport) {
    clear_has_event();
    auto* temp = _impl_.event_.execution_report_;
    _impl_.event_.execution_report_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_execution_report(::markethub::messaging::trading::ExecutionReport* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_execution_report();
    _impl_.event_.execution_report_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.execution_report)
}
inline ::markethub::messaging::trading::ExecutionReport* EventWrapper::_internal_mutable_execution_report() {
  if (event_case() != kExecutionReport) {
    clear_event();
    set_has_execution_report();
    _impl_.event_.execution_report_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::trading::ExecutionReport>(GetArena());
  }
  return _impl_.event_.execution_report_;
}
inline ::markethub::messaging::trading::ExecutionReport* EventWrapper::mutable_execution_report() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::trading::ExecutionReport* _msg = _internal_mutable_execution_report();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.execution_report)
  return _msg;
}

// .markethub.messaging.events.strategy.StrategyExecutionStarted strategy_execution_started = 6;
inline bool EventWrapper::has_strategy_execution_started() const {
  return event_case() == kStrategyExecutionStarted;
}
inline bool EventWrapper::_internal_has_strategy_execution_started() const {
  return event_case() == kStrategyExecutionStarted;
}
inline void EventWrapper::set_has_strategy_execution_started() {
  _impl_._oneof_case_[0] = kStrategyExecutionStarted;
}
inline ::markethub::messaging::events::strategy::StrategyExecutionStarted* EventWrapper::release_strategy_execution_started() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.strategy_execution_started)
  if (event_case() == kStrategyExecutionStarted) {
    clear_has_event();
    auto* temp = _impl_.event_.strategy_execution_started_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.strategy_execution_started_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::events::strategy::StrategyExecutionStarted& EventWrapper::_internal_strategy_execution_started() const {
  return event_case() == kStrategyExecutionStarted ? *_impl_.event_.strategy_execution_started_ : reinterpret_cast<::markethub::messaging::events::strategy::StrategyExecutionStarted&>(::markethub::messaging::events::strategy::_StrategyExecutionStarted_default_instance_);
}
inline const ::markethub::messaging::events::strategy::StrategyExecutionStarted& EventWrapper::strategy_execution_started() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.strategy_execution_started)
  return _internal_strategy_execution_started();
}
inline ::markethub::messaging::events::strategy::StrategyExecutionStarted* EventWrapper::unsafe_arena_release_strategy_execution_started() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.strategy_execution_started)
  if (event_case() == kStrategyExecutionStarted) {
    clear_has_event();
    auto* temp = _impl_.event_.strategy_execution_started_;
    _impl_.event_.strategy_execution_started_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_strategy_execution_started(::markethub::messaging::events::strategy::StrategyExecutionStarted* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_strategy_execution_started();
    _impl_.event_.strategy_execution_started_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.strategy_execution_started)
}
inline ::markethub::messaging::events::strategy::StrategyExecutionStarted* EventWrapper::_internal_mutable_strategy_execution_started() {
  if (event_case() != kStrategyExecutionStarted) {
    clear_event();
    set_has_strategy_execution_started();
    _impl_.event_.strategy_execution_started_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::events::strategy::StrategyExecutionStarted>(GetArena());
  }
  return _impl_.event_.strategy_execution_started_;
}
inline ::markethub::messaging::events::strategy::StrategyExecutionStarted* EventWrapper::mutable_strategy_execution_started() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::events::strategy::StrategyExecutionStarted* _msg = _internal_mutable_strategy_execution_started();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.strategy_execution_started)
  return _msg;
}

// .markethub.messaging.events.strategy.OnData on_data = 7;
inline bool EventWrapper::has_on_data() const {
  return event_case() == kOnData;
}
inline bool EventWrapper::_internal_has_on_data() const {
  return event_case() == kOnData;
}
inline void EventWrapper::set_has_on_data() {
  _impl_._oneof_case_[0] = kOnData;
}
inline ::markethub::messaging::events::strategy::OnData* EventWrapper::release_on_data() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.on_data)
  if (event_case() == kOnData) {
    clear_has_event();
    auto* temp = _impl_.event_.on_data_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.on_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::events::strategy::OnData& EventWrapper::_internal_on_data() const {
  return event_case() == kOnData ? *_impl_.event_.on_data_ : reinterpret_cast<::markethub::messaging::events::strategy::OnData&>(::markethub::messaging::events::strategy::_OnData_default_instance_);
}
inline const ::markethub::messaging::events::strategy::OnData& EventWrapper::on_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.on_data)
  return _internal_on_data();
}
inline ::markethub::messaging::events::strategy::OnData* EventWrapper::unsafe_arena_release_on_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.on_data)
  if (event_case() == kOnData) {
    clear_has_event();
    auto* temp = _impl_.event_.on_data_;
    _impl_.event_.on_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_on_data(::markethub::messaging::events::strategy::OnData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_on_data();
    _impl_.event_.on_data_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.on_data)
}
inline ::markethub::messaging::events::strategy::OnData* EventWrapper::_internal_mutable_on_data() {
  if (event_case() != kOnData) {
    clear_event();
    set_has_on_data();
    _impl_.event_.on_data_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::events::strategy::OnData>(GetArena());
  }
  return _impl_.event_.on_data_;
}
inline ::markethub::messaging::events::strategy::OnData* EventWrapper::mutable_on_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::events::strategy::OnData* _msg = _internal_mutable_on_data();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.on_data)
  return _msg;
}

// .markethub.messaging.events.strategy.EndOnData end_on_data = 8;
inline bool EventWrapper::has_end_on_data() const {
  return event_case() == kEndOnData;
}
inline bool EventWrapper::_internal_has_end_on_data() const {
  return event_case() == kEndOnData;
}
inline void EventWrapper::set_has_end_on_data() {
  _impl_._oneof_case_[0] = kEndOnData;
}
inline ::markethub::messaging::events::strategy::EndOnData* EventWrapper::release_end_on_data() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.end_on_data)
  if (event_case() == kEndOnData) {
    clear_has_event();
    auto* temp = _impl_.event_.end_on_data_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.end_on_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::events::strategy::EndOnData& EventWrapper::_internal_end_on_data() const {
  return event_case() == kEndOnData ? *_impl_.event_.end_on_data_ : reinterpret_cast<::markethub::messaging::events::strategy::EndOnData&>(::markethub::messaging::events::strategy::_EndOnData_default_instance_);
}
inline const ::markethub::messaging::events::strategy::EndOnData& EventWrapper::end_on_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.end_on_data)
  return _internal_end_on_data();
}
inline ::markethub::messaging::events::strategy::EndOnData* EventWrapper::unsafe_arena_release_end_on_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.end_on_data)
  if (event_case() == kEndOnData) {
    clear_has_event();
    auto* temp = _impl_.event_.end_on_data_;
    _impl_.event_.end_on_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_end_on_data(::markethub::messaging::events::strategy::EndOnData* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_end_on_data();
    _impl_.event_.end_on_data_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.end_on_data)
}
inline ::markethub::messaging::events::strategy::EndOnData* EventWrapper::_internal_mutable_end_on_data() {
  if (event_case() != kEndOnData) {
    clear_event();
    set_has_end_on_data();
    _impl_.event_.end_on_data_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::events::strategy::EndOnData>(GetArena());
  }
  return _impl_.event_.end_on_data_;
}
inline ::markethub::messaging::events::strategy::EndOnData* EventWrapper::mutable_end_on_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::events::strategy::EndOnData* _msg = _internal_mutable_end_on_data();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.end_on_data)
  return _msg;
}

// .markethub.messaging.events.strategy.OnExecutionReport on_execution_report = 9;
inline bool EventWrapper::has_on_execution_report() const {
  return event_case() == kOnExecutionReport;
}
inline bool EventWrapper::_internal_has_on_execution_report() const {
  return event_case() == kOnExecutionReport;
}
inline void EventWrapper::set_has_on_execution_report() {
  _impl_._oneof_case_[0] = kOnExecutionReport;
}
inline ::markethub::messaging::events::strategy::OnExecutionReport* EventWrapper::release_on_execution_report() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.on_execution_report)
  if (event_case() == kOnExecutionReport) {
    clear_has_event();
    auto* temp = _impl_.event_.on_execution_report_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.on_execution_report_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::events::strategy::OnExecutionReport& EventWrapper::_internal_on_execution_report() const {
  return event_case() == kOnExecutionReport ? *_impl_.event_.on_execution_report_ : reinterpret_cast<::markethub::messaging::events::strategy::OnExecutionReport&>(::markethub::messaging::events::strategy::_OnExecutionReport_default_instance_);
}
inline const ::markethub::messaging::events::strategy::OnExecutionReport& EventWrapper::on_execution_report() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.on_execution_report)
  return _internal_on_execution_report();
}
inline ::markethub::messaging::events::strategy::OnExecutionReport* EventWrapper::unsafe_arena_release_on_execution_report() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.on_execution_report)
  if (event_case() == kOnExecutionReport) {
    clear_has_event();
    auto* temp = _impl_.event_.on_execution_report_;
    _impl_.event_.on_execution_report_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_on_execution_report(::markethub::messaging::events::strategy::OnExecutionReport* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_on_execution_report();
    _impl_.event_.on_execution_report_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.on_execution_report)
}
inline ::markethub::messaging::events::strategy::OnExecutionReport* EventWrapper::_internal_mutable_on_execution_report() {
  if (event_case() != kOnExecutionReport) {
    clear_event();
    set_has_on_execution_report();
    _impl_.event_.on_execution_report_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::events::strategy::OnExecutionReport>(GetArena());
  }
  return _impl_.event_.on_execution_report_;
}
inline ::markethub::messaging::events::strategy::OnExecutionReport* EventWrapper::mutable_on_execution_report() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::events::strategy::OnExecutionReport* _msg = _internal_mutable_on_execution_report();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.on_execution_report)
  return _msg;
}

// .markethub.messaging.events.strategy.Statistics statistics = 10;
inline bool EventWrapper::has_statistics() const {
  return event_case() == kStatistics;
}
inline bool EventWrapper::_internal_has_statistics() const {
  return event_case() == kStatistics;
}
inline void EventWrapper::set_has_statistics() {
  _impl_._oneof_case_[0] = kStatistics;
}
inline ::markethub::messaging::events::strategy::Statistics* EventWrapper::release_statistics() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.statistics)
  if (event_case() == kStatistics) {
    clear_has_event();
    auto* temp = _impl_.event_.statistics_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.statistics_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::events::strategy::Statistics& EventWrapper::_internal_statistics() const {
  return event_case() == kStatistics ? *_impl_.event_.statistics_ : reinterpret_cast<::markethub::messaging::events::strategy::Statistics&>(::markethub::messaging::events::strategy::_Statistics_default_instance_);
}
inline const ::markethub::messaging::events::strategy::Statistics& EventWrapper::statistics() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.statistics)
  return _internal_statistics();
}
inline ::markethub::messaging::events::strategy::Statistics* EventWrapper::unsafe_arena_release_statistics() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.statistics)
  if (event_case() == kStatistics) {
    clear_has_event();
    auto* temp = _impl_.event_.statistics_;
    _impl_.event_.statistics_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_statistics(::markethub::messaging::events::strategy::Statistics* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_statistics();
    _impl_.event_.statistics_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.statistics)
}
inline ::markethub::messaging::events::strategy::Statistics* EventWrapper::_internal_mutable_statistics() {
  if (event_case() != kStatistics) {
    clear_event();
    set_has_statistics();
    _impl_.event_.statistics_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::events::strategy::Statistics>(GetArena());
  }
  return _impl_.event_.statistics_;
}
inline ::markethub::messaging::events::strategy::Statistics* EventWrapper::mutable_statistics() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::events::strategy::Statistics* _msg = _internal_mutable_statistics();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.statistics)
  return _msg;
}

// .markethub.messaging.events.strategy.OnParamsChanged on_params_changed = 11;
inline bool EventWrapper::has_on_params_changed() const {
  return event_case() == kOnParamsChanged;
}
inline bool EventWrapper::_internal_has_on_params_changed() const {
  return event_case() == kOnParamsChanged;
}
inline void EventWrapper::set_has_on_params_changed() {
  _impl_._oneof_case_[0] = kOnParamsChanged;
}
inline ::markethub::messaging::events::strategy::OnParamsChanged* EventWrapper::release_on_params_changed() {
  // @@protoc_insertion_point(field_release:markethub.messaging.events.EventWrapper.on_params_changed)
  if (event_case() == kOnParamsChanged) {
    clear_has_event();
    auto* temp = _impl_.event_.on_params_changed_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.event_.on_params_changed_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::markethub::messaging::events::strategy::OnParamsChanged& EventWrapper::_internal_on_params_changed() const {
  return event_case() == kOnParamsChanged ? *_impl_.event_.on_params_changed_ : reinterpret_cast<::markethub::messaging::events::strategy::OnParamsChanged&>(::markethub::messaging::events::strategy::_OnParamsChanged_default_instance_);
}
inline const ::markethub::messaging::events::strategy::OnParamsChanged& EventWrapper::on_params_changed() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:markethub.messaging.events.EventWrapper.on_params_changed)
  return _internal_on_params_changed();
}
inline ::markethub::messaging::events::strategy::OnParamsChanged* EventWrapper::unsafe_arena_release_on_params_changed() {
  // @@protoc_insertion_point(field_unsafe_arena_release:markethub.messaging.events.EventWrapper.on_params_changed)
  if (event_case() == kOnParamsChanged) {
    clear_has_event();
    auto* temp = _impl_.event_.on_params_changed_;
    _impl_.event_.on_params_changed_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void EventWrapper::unsafe_arena_set_allocated_on_params_changed(::markethub::messaging::events::strategy::OnParamsChanged* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_event();
  if (value) {
    set_has_on_params_changed();
    _impl_.event_.on_params_changed_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:markethub.messaging.events.EventWrapper.on_params_changed)
}
inline ::markethub::messaging::events::strategy::OnParamsChanged* EventWrapper::_internal_mutable_on_params_changed() {
  if (event_case() != kOnParamsChanged) {
    clear_event();
    set_has_on_params_changed();
    _impl_.event_.on_params_changed_ =
        ::google::protobuf::Message::DefaultConstruct<::markethub::messaging::events::strategy::OnParamsChanged>(GetArena());
  }
  return _impl_.event_.on_params_changed_;
}
inline ::markethub::messaging::events::strategy::OnParamsChanged* EventWrapper::mutable_on_params_changed() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::markethub::messaging::events::strategy::OnParamsChanged* _msg = _internal_mutable_on_params_changed();
  // @@protoc_insertion_point(field_mutable:markethub.messaging.events.EventWrapper.on_params_changed)
  return _msg;
}

inline bool EventWrapper::has_event() const {
  return event_case() != EVENT_NOT_SET;
}
inline void EventWrapper::clear_has_event() {
  _impl_._oneof_case_[0] = EVENT_NOT_SET;
}
inline EventWrapper::EventCase EventWrapper::event_case() const {
  return EventWrapper::EventCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace events
}  // namespace messaging
}  // namespace markethub


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_events_2eproto_2epb_2eh
